# Generated by Django 2.2.2 on 2021-07-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Comment', verbose_name='Коментарий'),
            preserve_default=False,
        ),
    ]
