# Generated by Django 3.1.7 on 2021-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0002_auto_20210718_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='smtpemail',
            field=models.CharField(blank=True, max_length=50, verbose_name='SMTPemail'),
        ),
        migrations.AddField(
            model_name='setting',
            name='smtppassword',
            field=models.CharField(blank=True, max_length=50, verbose_name='SMTPpassword'),
        ),
        migrations.AddField(
            model_name='setting',
            name='smtpport',
            field=models.CharField(blank=True, max_length=8, verbose_name='SMTPport'),
        ),
        migrations.AddField(
            model_name='setting',
            name='smtpserver',
            field=models.CharField(blank=True, max_length=50, verbose_name='SMTPserver'),
        ),
    ]
