# Generated by Django 3.1.12 on 2021-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0005_auto_20210725_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
    ]
