# Generated by Django 3.1.12 on 2021-07-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0006_auto_20210726_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
    ]
