# Generated by Django 2.2.2 on 2021-07-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punct', models.CharField(max_length=255, verbose_name='Населеный пункт')),
            ],
            options={
                'verbose_name': 'Населеный пункт',
                'verbose_name_plural': 'Населеные пункты',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, verbose_name='Школа')),
                ('punct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Punkt', verbose_name='Населеный пункт')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школа',
            },
        ),
        migrations.CreateModel(
            name='Klas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=30, verbose_name='Статус')),
                ('alf', models.CharField(choices=[('1', 'А'), ('2', 'Б'), ('3', 'В'), ('4', 'Г'), ('5', 'Д'), ('6', 'Е'), ('7', 'Ё'), ('8', 'Ж'), ('9', 'З'), ('10', 'И'), ('11', 'Й'), ('12', 'К'), ('13', 'Л'), ('14', 'М'), ('15', 'Н')], max_length=30, verbose_name='Статус')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Класс',
            },
        ),
    ]
