# Generated by Django 3.2.5 on 2021-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Telephone', ' Телефон'), ('Email', 'Почта')], default='Telephone', max_length=30, verbose_name='Способ связи')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('firstname', models.CharField(db_index=True, max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('text', models.TextField(max_length=255, verbose_name='Текст')),
                ('soglasen', models.BooleanField(default=False, verbose_name='Согласен на обработку персональный данных')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
