# Generated by Django 3.1.12 on 2021-07-27 04:59

from django.db import migrations, models
import django.db.models.deletion
import faicon.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.CharField(max_length=255, verbose_name='Подвал')),
            ],
            options={
                'verbose_name': 'Подвал',
                'verbose_name_plural': 'Подвал',
            },
        ),
        migrations.CreateModel(
            name='Ikonki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('icon', faicon.fields.FAIconField(max_length=50, verbose_name='Иконка')),
                ('sylka', models.CharField(max_length=30, verbose_name='Сылка')),
                ('status', models.CharField(choices=[('True', 'Опубликовать'), ('False', 'Не публиковать')], max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='Vidjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidjetone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vidjetone', to='news.category', verbose_name='Виджет-1')),
                ('vidjetthree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vidjetthree', to='news.category', verbose_name='Виджет-3')),
                ('vidjettwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vidjettwo', to='news.category', verbose_name='Виджет-2')),
            ],
            options={
                'verbose_name': 'Троица категории',
                'verbose_name_plural': 'Троица категорий',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Publish', 'Опубликовать'), ('Not_to_publish', 'Не публиковать')], default='Publish', max_length=30, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='Изображение')),
                ('views', models.IntegerField(default=0, null=True, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Slidertitle', to='news.post', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Saidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saidebar', models.ManyToManyField(related_name='saidebar', to='news.Category', verbose_name='Список')),
            ],
            options={
                'verbose_name': 'Сайдбар',
                'verbose_name_plural': 'Сайдбар',
            },
        ),
        migrations.CreateModel(
            name='Punct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punct', models.CharField(max_length=255, verbose_name='меню')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='glavnaya.menu')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='glavnaya.punct', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.ManyToManyField(related_name='favourites', to='news.Category', verbose_name='Список')),
            ],
            options={
                'verbose_name': 'Избранная категория',
                'verbose_name_plural': 'Избранные категорий',
            },
        ),
        migrations.CreateModel(
            name='Favorit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit', to='news.category', verbose_name='Ибранная категория')),
            ],
            options={
                'verbose_name': 'Ибранная категория',
                'verbose_name_plural': 'Ибранная категория',
            },
        ),
    ]
