# Generated by Django 3.1.12 on 2021-07-26 11:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default=1, max_length=30, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Punct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punct', models.CharField(max_length=255, verbose_name='меню')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='glavnaya.menu')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='glavnaya.punct', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
    ]
