# Generated by Django 3.1.12 on 2021-07-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0006_auto_20210726_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chelensoveta',
            options={'verbose_name': 'Члены совета', 'verbose_name_plural': 'Члены совета'},
        ),
    ]
