# Generated by Django 3.1.12 on 2021-07-27 14:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0007_auto_20210726_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='sovet',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание'),
        ),
    ]
