# Generated by Django 3.2.5 on 2021-07-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smena', '0002_alter_smena_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'рубрики смены', 'verbose_name_plural': 'рубрика смены'},
        ),
    ]
