# Generated by Django 3.2.5 on 2021-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena', '0004_auto_20210718_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smena',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
